services:
  - type: web
    name: ring-wing-frontend
    runtime: static
    buildCommand: npm install --legacy-peer-deps && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://rwmobile.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html